{
 "title": "HCP Vault Copy certa",
 "description": " Hashicorp Vault Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster:", "query": { "query": "label_values(cluster_id)" } },
   {
    "name": "project",
    "query": {
     "query": "label_values(vault_runtime_alloc_bytes{cluster_id=\"$cluster\"}, project_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vault status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (1 + vault_core_unsealed)",
     "legendFormat": "Vault Node: {{instance}}"
    }
   ]
  },
  {
   "title": "Identity Entities by Namespace",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg by (namespace) (vault_identity_entity_count{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "KV Secrets by Mount",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(mount_point) (vault_secret_kv_count{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Leases",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{cluster_id=\"$cluster\"})"
    }
   ]
  },
  { "title": "Instances status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100\r\n",
     "legendFormat": "Vault: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (instance) (\r\n    node_filesystem_size_bytes{cluster_id=\"$cluster\", fstype!~\"tmpfs|overlay|cgroup2?\"}\r\n  )\r\n  -\r\n  sum by (instance) (\r\n    node_filesystem_free_bytes{cluster_id=\"$cluster\", fstype!~\"tmpfs|overlay|cgroup2?\"}\r\n  )\r\n)\r\n/\r\nsum by (instance) (\r\n  node_filesystem_size_bytes{cluster_id=\"$cluster\", fstype!~\"tmpfs|overlay|cgroup2?\"}\r\n)\r\n",
     "legendFormat": "Vault Node: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (instance) (node_memory_MemTotal_bytes{cluster_id=\"$cluster\"})\r\n  -\r\n  sum by (instance) (node_memory_MemAvailable_bytes{cluster_id=\"$cluster\"})\r\n)\r\n/\r\nsum by (instance) (node_memory_MemTotal_bytes{cluster_id=\"$cluster\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_token_count{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Available Tokens by Policy",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_token_count_by_policy{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Available Tokens by TTL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_token_count_by_ttl{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_token_count_by_auth{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Batch and Service Tokens by Methods & TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation{cluster_id=\"$cluster\"})",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count{cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  }
 ]
}